"use client";

import React, { useState, useRef } from "react";
import { Upload, Image as ImageIcon, Sparkles, Send, Loader2, Info, X, Download, Settings, Save, CheckCircle2, AlertCircle } from "lucide-react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { motion, AnimatePresence } from "framer-motion";
import { cn } from "@/lib/utils";

export default function Home() {
  const [prompt, setPrompt] = useState("");
  const [image, setImage] = useState<string | null>(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [analysis, setAnalysis] = useState<string>("");
  const [isSettingsOpen, setIsSettingsOpen] = useState(false);
  const [savePath, setSavePath] = useState(typeof window !== "undefined" ? localStorage.getItem("obsidian_save_path") || "" : "");
  const [saveStatus, setSaveStatus] = useState<"idle" | "saving" | "success" | "error">("idle");
  const [statusMessage, setStatusMessage] = useState("");
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        setImage(reader.result as string);
      };
      reader.readAsDataURL(file);
    }
  };
  const handleAnalyze = async () => {
    if (!prompt && !image) return;

    setIsAnalyzing(true);
    setAnalysis("");

    try {
      const response = await fetch("/api/analyze", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ prompt, image }),
      });

      if (!response.body) return;
      const reader = response.body.getReader();
      const decoder = new TextDecoder();

      while (true) {
        const { value, done } = await reader.read();
        if (done) break;
        const chunk = decoder.decode(value);
        setAnalysis((prev) => prev + chunk);
      }
    } catch (error) {
      console.error("Analysis failed:", error);
      setAnalysis("解析中にエラーが発生しました。");
    } finally {
      setIsAnalyzing(false);
    }
  };
  const handleDownloadObsidian = async () => {
    if (!analysis) return;

    const date = new Date().toISOString().split('T')[0];
    const briefPrompt = prompt.slice(0, 20).replace(/[^\w\s-]/g, '').trim() || "analysis";
    const fileName = `${date}_${briefPrompt}.md`;

    let markdown = `---
date: ${new Date().toLocaleString('ja-JP')}
prompt: |
  ${prompt.replace(/\n/g, '\n  ')}
tags: [stable-diffusion, prompt-analysis]
---

# SD Prompt Analysis - ${date}

## 🖼️ Reference Image
${image ? `![[${image}]]` : "No image attached."}

${analysis}

---
*Generated by SD Prompt Analyzer*
`;

    if (image) {
      markdown = markdown.replace(`![[${image}]]`, `![Reference Image](${image})`);
    }

    // Try direct save if path is set
    if (savePath) {
      setSaveStatus("saving");
      try {
        const res = await fetch("/api/save", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ folderPath: savePath, fileName, content: markdown }),
        });
        const data = await res.json();
        if (data.success) {
          setSaveStatus("success");
          setStatusMessage(`Saved to ${savePath}`);
          setTimeout(() => setSaveStatus("idle"), 3000);
          return;
        } else {
          throw new Error(data.error);
        }
      } catch (err: any) {
        console.error("Direct save failed, falling back to download:", err);
        setSaveStatus("error");
        setStatusMessage(err.message || "Direct save failed.");
        setTimeout(() => setSaveStatus("idle"), 3000);
      }
    }

    // Fallback to browser download
    const blob = new Blob([markdown], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = fileName;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleSavePathUpdate = (path: string) => {
    setSavePath(path);
    localStorage.setItem("obsidian_save_path", path);
  };

  return (
    <main className="min-h-screen p-4 md:p-8 max-w-5xl mx-auto space-y-8 pb-20">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 border-b border-white/5 pb-8 relative">
        <div className="space-y-2">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-indigo-500/10 flex items-center justify-center border border-indigo-500/20">
              <Sparkles className="text-indigo-400" size={20} />
            </div>
            <h1 className="text-2xl md:text-3xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-white via-zinc-200 to-zinc-500">
              SD Prompt Analyzer
            </h1>
          </div>
          <p className="text-zinc-500 text-sm md:text-base ml-1">
            Grok-3 Powered • Prompt Debugging • Beginner Friendly
          </p>
        </div>

        <button
          onClick={() => setIsSettingsOpen(!isSettingsOpen)}
          className="p-3 bg-white/5 hover:bg-white/10 text-zinc-400 hover:text-white rounded-xl transition-all border border-white/5 shadow-sm"
        >
          <Settings size={20} />
        </button>

        {/* Settings Modal */}
        <AnimatePresence>
          {isSettingsOpen && (
            <motion.div
              initial={{ opacity: 0, y: 10, scale: 0.95 }}
              animate={{ opacity: 1, y: 0, scale: 1 }}
              exit={{ opacity: 0, y: 10, scale: 0.95 }}
              className="absolute top-full right-0 mt-4 w-full md:w-96 bg-zinc-900 border border-white/10 rounded-2xl p-6 shadow-2xl z-50 backdrop-blur-xl"
            >
              <div className="flex items-center justify-between mb-6">
                <h3 className="text-lg font-semibold text-white flex items-center gap-2">
                  <Settings size={18} className="text-indigo-400" />
                  保存設定
                </h3>
                <button onClick={() => setIsSettingsOpen(false)} className="text-zinc-500 hover:text-white">
                  <X size={18} />
                </button>
              </div>
              <div className="space-y-4">
                <div className="space-y-2">
                  <label className="text-xs font-semibold text-zinc-400 uppercase tracking-wider">
                    Obsidian保存先フォルダ (絶対パス)
                  </label>
                  <input
                    type="text"
                    value={savePath}
                    onChange={(e) => handleSavePathUpdate(e.target.value)}
                    placeholder="C:\Users\Name\Documents\Obsidian\MyVault"
                    className="w-full bg-black/40 border border-white/10 rounded-xl px-4 py-3 text-sm text-zinc-200 focus:outline-none focus:border-indigo-500/50 transition-all placeholder:text-zinc-700"
                  />
                  <p className="text-[10px] text-zinc-500 leading-relaxed italic">
                    ※未設定の場合は、通常のブラウザダウンロードとなります。
                  </p>
                </div>
                <div className="pt-2">
                  <button
                    onClick={() => setIsSettingsOpen(false)}
                    className="w-full py-3 bg-indigo-500/10 hover:bg-indigo-500/20 text-indigo-400 rounded-xl text-sm font-medium transition-all"
                  >
                    設定を閉じる
                  </button>
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        {/* Left Column: Input */}
        <div className="lg:col-span-5 space-y-6">
          <section className="glass rounded-3xl p-6 space-y-6">
            <div className="space-y-4">
              <label className="text-sm font-medium text-zinc-300 flex items-center gap-2">
                <Send size={16} /> Stable Diffusion プロンプト
              </label>
              <textarea
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                placeholder="masterpiece, best quality, girl with blue eyes..."
                className="w-full h-48 bg-white/5 border border-white/10 rounded-2xl p-4 focus:ring-2 focus:ring-blue-500 outline-none transition-all resize-none text-zinc-100 placeholder:text-zinc-600"
              />
            </div>

            <div className="space-y-4">
              <label className="text-sm font-medium text-zinc-300 flex items-center gap-2">
                <ImageIcon size={16} /> 参考画像 (Optional - Vision解析用)
              </label>
              <div
                onClick={() => fileInputRef.current?.click()}
                className={cn(
                  "border-2 border-dashed border-white/10 rounded-2xl aspect-video flex flex-col items-center justify-center cursor-pointer hover:bg-white/5 transition-all relative overflow-hidden",
                  image && "border-blue-500/50"
                )}
              >
                {image ? (
                  <>
                    <img src={image} alt="Uploaded" className="w-full h-full object-cover" />
                    <button
                      onClick={(e) => { e.stopPropagation(); setImage(null); }}
                      className="absolute top-2 right-2 p-1.5 bg-black/60 rounded-full hover:bg-black/80 text-white transition-all shadow-lg"
                    >
                      <X size={16} />
                    </button>
                  </>
                ) : (
                  <div className="text-center space-y-2">
                    <Upload className="mx-auto text-zinc-500" />
                    <p className="text-zinc-500 text-sm">画像をドラッグ＆ドロップまたはクリック</p>
                  </div>
                )}
                <input type="file" ref={fileInputRef} hidden accept="image/*" onChange={handleImageUpload} />
              </div>
            </div>

            <button
              onClick={handleAnalyze}
              disabled={isAnalyzing || (!prompt && !image)}
              className="w-full bg-blue-600 hover:bg-blue-500 disabled:bg-zinc-800 disabled:text-zinc-500 py-4 rounded-2xl font-semibold flex items-center justify-center gap-2 transition-all shadow-xl shadow-blue-900/20"
            >
              {isAnalyzing ? <Loader2 className="animate-spin" /> : <Sparkles />}
              {isAnalyzing ? "解析中..." : "解析と診断を開始"}
            </button>
          </section>
        </div>

        {/* Right Column: Results */}
        <div className="lg:col-span-7 space-y-6">
          <AnimatePresence mode="wait">
            {(analysis || isAnalyzing) ? (
              <motion.section
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -20 }}
                className="glass rounded-3xl p-6 md:p-8 h-[700px] overflow-y-auto relative"
              >
                {isAnalyzing && !analysis && (
                  <div className="absolute inset-0 flex items-center justify-center bg-black/20 backdrop-blur-sm z-10 rounded-3xl">
                    <div className="text-center space-y-4">
                      <Loader2 className="animate-spin mx-auto text-blue-500" size={40} />
                      <p className="text-zinc-400 font-medium animate-pulse">Grok が思考しています...</p>
                    </div>
                  </div>
                )}

                <div className="prose prose-invert prose-blue max-w-none">
                  <ReactMarkdown remarkPlugins={[remarkGfm]}>
                    {analysis}
                  </ReactMarkdown>
                </div>

                {!isAnalyzing && analysis && (
                  <div className="mt-8 pt-6 border-t border-white/10 flex flex-col md:flex-row md:items-center justify-between gap-4">
                    <div className="flex items-center gap-3 text-sm">
                      {saveStatus === "saving" && (
                        <div className="flex items-center gap-2 text-zinc-400 animate-pulse">
                          <Loader2 size={16} className="animate-spin" />
                          保存中...
                        </div>
                      )}
                      {saveStatus === "success" && (
                        <div className="flex items-center gap-2 text-emerald-400">
                          <CheckCircle2 size={16} />
                          {savePath ? "フォルダに保存しました" : "ダウンロードを開始しました"}
                        </div>
                      )}
                      {saveStatus === "error" && (
                        <div className="flex items-center gap-2 text-rose-400">
                          <AlertCircle size={16} />
                          {statusMessage}
                        </div>
                      )}
                    </div>

                    <button
                      onClick={handleDownloadObsidian}
                      className="flex items-center gap-2 px-6 py-3 bg-zinc-100 hover:bg-white text-zinc-950 rounded-2xl transition-all shadow-lg text-sm font-bold active:scale-95 disabled:opacity-50"
                      disabled={saveStatus === "saving"}
                    >
                      <Download size={18} />
                      {savePath ? "Obsidianに直接保存" : "Obsidianに保存 (.md)"}
                    </button>
                  </div>
                )}
              </motion.section>
            ) : (
              <div className="h-full flex flex-col items-center justify-center text-center p-8 border-2 border-dashed border-white/5 rounded-3xl opacity-50 space-y-4">
                <Info size={48} className="text-zinc-600" />
                <p className="text-zinc-500">プロンプトを入力して解析を開始してください</p>
              </div>
            )}
          </AnimatePresence>
        </div>
      </div>
    </main>
  );
}
